Import from: prelink-cross-test.patch
Source: Wind River Systems

The purpose of this patch is to allow for the testsuite to be run
using the cross prelink.  This disables the run-time test, but will
keep all of the prelink testing.  To have full test coverage you will
want to execute these tests on the target as well.

diff --git a/testsuite/Makefile.in b/testsuite/Makefile.in
--- a/testsuite/Makefile.in
+++ b/testsuite/Makefile.in
@@ -161,7 +161,9 @@ check-TESTS: $(TESTS)
 	    if test -f ./$$tst; then dir=./; \
 	    elif test -f $$tst; then dir=; \
 	    else dir="$(srcdir)/"; fi; \
-	    if $(TESTS_ENVIRONMENT) $${dir}$$tst; then \
+	    $(TESTS_ENVIRONMENT) $${dir}$$tst; \
+	    ret=$$?; \
+	    if test $$ret -eq 0; then \
 	      all=`expr $$all + 1`; \
 	      case " $(XFAIL_TESTS) " in \
 	      *" $$tst "*) \
@@ -173,16 +175,16 @@ check-TESTS: $(TESTS)
 	        echo "PASS: $$tst"; \
 	      ;; \
 	      esac; \
-	    elif test $$? -ne 77; then \
+	    elif test $$ret -ne 77; then \
 	      all=`expr $$all + 1`; \
 	      case " $(XFAIL_TESTS) " in \
 	      *" $$tst "*) \
 	        xfail=`expr $$xfail + 1`; \
-	        echo "XFAIL: $$tst"; \
+	        echo "XFAIL: $$tst ($$ret)"; \
 	      ;; \
 	      *) \
 	        failed=`expr $$failed + 1`; \
-	        echo "FAIL: $$tst"; \
+	        echo "FAIL: $$tst ($$ret)"; \
 	      ;; \
 	      esac; \
 	    fi; \
